apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views as home_views

app_name = 'apps_home'
urlpatterns = [
    # The home page
    path('', home_views.index, name='index'),
    path('dashboard', home_views.dashboard, name='dashboard'), 
    path('test', home_views.test, name='test'), 
    path('Registration', home_views.create_user, name='Registration'), # Using the 'index' function from the 'home' views
    path ('products', home_views.ProductView.as_view(), name='products'),
    path('user_create_info/<int:pk>/', home_views.create_user_details, name='user_create_info'),
    path('user_detail', home_views.user_detail, name='user_detail'),
    path('product_detail/<int:pk>', home_views.ProductDetials.as_view(), name='product_detail'),
    path('client_product_detail/<int:pk>', home_views.ClientProductDetail.as_view(), name='client_ProDetail'),
    path('transactionDetail/<int:pk>/', home_views.TransactionDetail.as_view(), name='transactionDetail'),
    #path('dashboard', home_views.cases_all, name='dashboard'),
   
    #path('cases_all', home_views.cases_all, name='cases_all'),
    
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include,re_path  # add this

urlpatterns = [
    path('admin/', admin.site.urls),                       # Django admin route
    path("", include("apps.authentication.urls")),        # Auth routes - login / register
    # ADD NEW Routes HERE
    path("", include("apps.home.urls")),                   # Include Home URLs
    #re_path(r'^messages/', include('django_messages.urls')),    # Include messages URLs
]

apps/templates/includes/mngt/fixed-plugin.html
{% load static %}

  <div class="fixed-plugin">
    <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
      <i class="fa fa-cog py-2"> </i>
    </a>
    <div class="card shadow-lg ">
      <div class="card-header pb-0 pt-3 ">
        <div class="float-start">
          <h5 class="mt-3 mb-0">Soft UI Configurator</h5>
          <p>See our dashboard options.</p>
        </div>
        <div class="float-end mt-4">
          <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
            <i class="fa fa-close"></i>
          </button>
        </div>
        <!-- End Toggle Button -->
      </div>
      <hr class="horizontal dark my-1">
      <div class="card-body pt-sm-3 pt-0">
        <!-- Sidebar Backgrounds -->
        <div>
          <h6 class="mb-0">Sidebar Colors</h6>
        </div>
        <a href="javascript:void(0)" class="switch-trigger background-color">
          <div class="badge-colors my-2 text-start">
            <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
          </div>
        </a>
        <!-- Sidenav Type -->
        <div class="mt-3">
          <h6 class="mb-0">Sidenav Type</h6>
          <p class="text-sm">Choose between 2 different sidenav types.</p>
        </div>
        <div class="d-flex">
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
        </div>
        <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
        <!-- Navbar Fixed -->
        <div class="mt-3">
          <h6 class="mb-0">Navbar Fixed</h6>
        </div>
        <div class="form-check form-switch ps-0">
          <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
        </div>
        <hr class="horizontal dark my-sm-4">
        <a target="_blank"
           class="btn bg-gradient-dark w-100" 
           href="https://appseed.us/product/soft-ui-dashboard/django/">Download</a>
        <a target="_blank"
           class="btn btn-outline-dark w-100" 
           href="https://docs.appseed.us/products/django-dashboards/soft-ui-dashboard/">DOCS</a>
      </div>
    </div>
  </div>

apps/templates/includes/mngt/footer-fullscreen.html
<!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
    <footer class="footer py-5">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mb-4 mx-auto text-center">
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              Company
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              About Us
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              Team
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              Products
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              Blog
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
              Pricing
            </a>
          </div>
          <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
              <span class="text-lg fab fa-dribbble"></span>
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
              <span class="text-lg fab fa-twitter"></span>
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
              <span class="text-lg fab fa-instagram"></span>
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
              <span class="text-lg fab fa-pinterest"></span>
            </a>
            <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
              <span class="text-lg fab fa-github"></span>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col-8 mx-auto text-center mt-1">
            <p class="mb-0 text-secondary">
              &copy; <a href="https://bit.ly/3fKQZaL" class="text-muted" target="_blank">Creative Tim</a> - coded by AppSeed.
            </p>
          </div>
        </div>
      </div>
    </footer>
    <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

apps/templates/includes/mngt/footer-rtl.html
<footer class="footer pt-3  ">
    <div class="container-fluid">
      <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6 mb-lg-0 mb-4">
          <div class="copyright text-center text-sm text-muted text-lg-end">
            &copy; <a href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> - coded by AppSeed.
          </div>
        </div>
        <div class="col-lg-6">
          <ul class="nav nav-footer justify-content-center justify-content-lg-end">
            <li class="nav-item">
              <a href="https://appseed.us/product/soft-ui-dashboard/django/" class="nav-link text-muted" target="_blank">Download</a>
            </li>
            <li class="nav-item">
              <a href="https://appseed.us/product/soft-ui-dashboard-pro/django/" 
                 class="nav-link text-muted" target="_blank">PRO Version</a>
            </li>
            <li class="nav-item">
              <a href="https://appseed.us/support/" class="nav-link text-muted" target="_blank">Support</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  

apps/templates/includes/mngt/footer.html
      <footer class="footer pt-3  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                &copy; <a href="https://bit.ly/3fKQZaL" class="text-muted" target="_blank">Creative Tim</a> - coded by AppSeed.
              </div>
            </div>
            <div class="col-lg-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://appseed.us/product/soft-ui-dashboard/django/" class="nav-link text-muted" target="_blank">Download</a>
                </li>
                <li class="nav-item">
                  <a href="https://appseed.us/product/soft-ui-dashboard-pro/django/" 
                     class="nav-link text-muted" target="_blank">PRO Version</a>
                </li>
                <li class="nav-item">
                  <a href="https://appseed.us/support/" class="nav-link text-muted" target="_blank">Support</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

apps/templates/includes/mngt/navigation-fullscreen.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
    <div class="container-fluid pe-0">
      <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="/">
        Soft UI Dashboard
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon mt-2">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </span>
      </button>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="navbar-nav mx-auto ms-xl-auto">
          
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center me-2 active" aria-current="page" href="/">
              <i class="fa fa-chart-pie opacity-6 me-1"></i>
              Dashboard
            </a>
          </li>

          <li class="nav-item">
            <label for="theme-switch" class="nav-link d-flex align-items-center me-2">
              <i class="fa fa-sun cursor-pointer opacity-6 px-1" id="theme-indicator"></i>
              Theme
            </label>
            <input type="checkbox" class="d-none" id="theme-switch"/>
          </li>
          
        </ul>

        <ul class="navbar-nav d-lg-block d-none">
          <li class="nav-item">
            <a target="_blank"
               href="https://appseed.us/product/soft-ui-dashboard/django/" 
               class="btn btn-sm btn-round mb-0 me-1 bg-gradient-dark">Download</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

apps/templates/includes/mngt/navigation-rtl.html
{% load static %}

<!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 ">
            <li class="breadcrumb-item text-sm ps-2"><a class="opacity-5 text-dark" href="javascript:;">لوحات القيادة</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">RTL</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">RTL</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 px-0" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group">
              <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
              <input type="text" class="form-control" placeholder="أكتب هنا...">
            </div>
          </div>
          <ul class="navbar-nav me-auto ms-0 justify-content-end">

            <li class="nav-item d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">يسجل دخول</span>
              </a>
            </li>
            <li class="nav-item d-xl-none pe-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
            <li class="nav-item px-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
              </a>
            </li>
            <li class="nav-item dropdown ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell cursor-pointer"></i>
              </a>
              <ul class="dropdown-menu  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="{% static 'img/team-2.jpg' %}" class="avatar avatar-sm  ms-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">رسالة جديدة</span> من لور
                        </h6>
                        <p class="text-xs text-secondary mb-0 ms-auto">
                          <i class="fa fa-clock me-1"></i>
                          منذ 13 دقيقة
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="{% static 'img/small-logos/logo-spotify.svg' %}" class="avatar avatar-sm bg-gradient-dark  ms-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">البوم جديد</span> بواسطة ترافيس سكوت
                        </h6>
                        <p class="text-xs text-secondary mb-0 ms-auto">
                          <i class="fa fa-clock me-1"></i>
                          يوم 1
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="avatar avatar-sm bg-gradient-secondary  ms-3  my-auto">
                        <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <title>credit-card</title>
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                              <g transform="translate(1716.000000, 291.000000)">
                                <g transform="translate(453.000000, 454.000000)">
                                  <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                  <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                </g>
                              </g>
                            </g>
                          </g>
                        </svg>
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          اكتمل الدفع بنجاح
                        </h6>
                        <p class="text-xs text-secondary mb-0 ms-auto">
                          <i class="fa fa-clock me-1"></i>
                          2 أيام
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <li class="nav-item ps-2 d-flex align-items-center">
              <label for="theme-switch" class="nav-link text-body p-0 m-0">
                <i class="fa fa-sun fixed-plugin-button-nav cursor-pointer" id="theme-indicator"></i>
              </label>
              <input type="checkbox" class="d-none" id="theme-switch"/>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->

apps/templates/includes/mngt/scripts.html
{% load static %}

<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script src="{% static 'js/dark-mode-handler.js' %}"></script>

apps/templates/includes/mngt/sidebar.html
{% load i18n static admin_soft %}

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 " id="sidenav-main">
  <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href="{% url 'admin:index' %}">
      <img src="{% static 'img/logo-ct-dark.png' %}" class="navbar-brand-img h-100" alt="main_logo">
      <span class="ms-1 font-weight-bold">Life Plus</span>
    </a>
  </div>
  <hr class="horizontal dark mt-0">
  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">

    
                <li class="nav-item">
                  <span class="nav-link d-flex justify-content-between align-items-center">
                    <span class="d-flex justify-content-between align-items-center">
                      <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="sidebar-icon "></span>
                      </div>
                      <a href="{% url 'apps_home:dashboard' %}">
                        <span class="nav-link-text ms-1">{% trans 'Dashboard' %}</span>
                      </a>
                    </span>
                  </span>
                </li>
              
                <li class="nav-item">
                  <span class="nav-link d-flex justify-content-between align-items-center">
                    <span class="d-flex justify-content-between align-items-center">
                      <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="sidebar-icon "></span>
                      </div>
                      <a href="{% url 'apps_home:products' %}">
                        <span class="nav-link-text ms-1">{% trans 'Products' %}</span>
                      </a>
                    </span>
                  </span>
                </li>
        
                <li class="nav-item">
                  <span class="nav-link d-flex justify-content-between align-items-center">
                    <span class="d-flex justify-content-between align-items-center">
                      <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="sidebar-icon "></span>
                      </div>
                      <a href="">
                        <span class="nav-link-text ms-1">{% trans 'Clients' %}</span>
                      </a>
                    </span>
                  </span>
                </li>

                <li class="nav-item">
                  <span class="nav-link d-flex justify-content-between align-items-center">
                    <span class="d-flex justify-content-between align-items-center">
                      <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="sidebar-icon "></span>
                      </div>
                      <a href="">
                        <span class="nav-link-text ms-1">{% trans 'Users' %}</span>
                      </a>
                    </span>
                  </span>
                </li>
    </ul>

  </div>
  
</aside>