apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views as home_views

app_name = 'apps_home'
urlpatterns = [
    # The home page
    path('', home_views.index, name='index'),
    path('dashboard', home_views.dashboard, name='dashboard'), 
    path('test', home_views.test, name='test'), 
    path('Registration', home_views.create_user, name='Registration'), # Using the 'index' function from the 'home' views
    path ('products', home_views.ProductView.as_view(), name='products'),
    path('user_create_info/<int:pk>/', home_views.create_user_details, name='user_create_info'),
    path('user_detail', home_views.user_detail, name='user_detail'),
    path('product_detail/<int:pk>', home_views.ProductDetials.as_view(), name='product_detail'),
    path('client_product_detail/<int:pk>', home_views.ClientProductDetail.as_view(), name='client_ProDetail'),
    path('transactionDetail/<int:pk>/', home_views.TransactionDetail.as_view(), name='transactionDetail'),
    #path('dashboard', home_views.cases_all, name='dashboard'),
   
    #path('cases_all', home_views.cases_all, name='cases_all'),
    
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include,re_path  # add this

urlpatterns = [
    path('admin/', admin.site.urls),                       # Django admin route
    path("", include("apps.authentication.urls")),        # Auth routes - login / register
    # ADD NEW Routes HERE
    path("", include("apps.home.urls")),                   # Include Home URLs
    #re_path(r'^messages/', include('django_messages.urls')),    # Include messages URLs
]

apps/home/forms.py
# forms.py
from django import forms
from .models import MyUser,Orders
from .models import Products


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username','password','first_name', 'last_name', 'dateofbirth','email', 'marital_status', 'gender', 'address', 'phone_number_1', 'phone_number_2','parent']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'dateofbirth': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'marital_status': forms.Select(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'phone_number_1': forms.TextInput(attrs={'class': 'form-control'}),
            'parent': forms.TextInput(attrs={'class': 'form-control', 'id': 'parent-select'}),
        }

class keyBonusUpdate(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['keyBonus']  
        widgets = {
            'keyBonus': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['keyBonus'].queryset = MyUser.objects.all()
       
        





class CreateProducts(forms.ModelForm):
    package_price = forms.DecimalField(widget=forms.TextInput(attrs={'class': 'form-control', 'pattern': '[0-9]*'}))
    class Meta:
        model = Products
        fields = ['package_name','package_price','bonus']
        widgets = {
            'package_name': forms.TextInput(attrs={'class': 'form-control'}),
            'bonus': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = '__all__'

apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
from django.shortcuts import redirect, render,get_object_or_404
from .models import *
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse, reverse_lazy
import random
import random_word
from .forms import *
from django.views.generic import ListView, CreateView,DetailView
from decimal import Decimal
from django.http import JsonResponse
from django.contrib import messages

def whistleblower_user():
    random_word_str = random_word.RandomWords().get_random_word()
    random_number = random.randint(1000, 9999)
    return f"{random_word_str}{random_number}"


#@login_required(login_url="/login/")

def test(request):
    context = {}
    html_template = loader.get_template('home/transactionList.html')
    return HttpResponse(html_template.render(context,request))


def index(request):
    products = Products.objects.all().values(),
    context = {
        'products': products
    }
    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context,request))

def dashboard(request):
    context = {}
    html_template = loader.get_template('home/dashboard.html')
    return HttpResponse(html_template.render(context,request))

@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))
    

class UserNode:
    def __init__(self, user, relationship=None):
        self.user = user
        self.relationship = relationship  # Indicates the relationship ('parent', 'child', 'grandchild', ...)
        self.children = []

    def add_child(self, child, relationship=None):
        child_node = UserNode(child, relationship)
        self.children.append(child_node)

    def show_hierarchy(self, depth=0, max_depth=10):
        hierarchy = {
            'user': self.user.username,
            'relationship': self.relationship if self.relationship else 'parent',
            'children': []
        }

        if depth < max_depth:
            for child in self.children:
                hierarchy['children'].append(child.show_hierarchy(depth + 1, max_depth))

        return hierarchy

def fetch_and_add_children(node, max_depth):
    if max_depth > 0:
        children = MyUser.objects.filter(parent=node.user)
        for child in children:
            node.add_child(child, relationship='child')
            fetch_and_add_children(node.children[-1], max_depth - 1)

def create_user(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            
            # Check if user with this username already exists
            if MyUser.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists. Please choose a different username.')
            else:
                user_instance = form.save(commit=False)
                password = form.cleaned_data['password']
                user_instance.set_password(password)

                if request.user.is_authenticated:
                    user_instance.parent = request.user

                user_instance.save()

                if request.user.is_authenticated:
                    parent_node = UserNode(request.user, relationship='parent')
                    children_under_parent = MyUser.objects.filter(parent=request.user)
                    
                    for child in children_under_parent:
                        parent_node.add_child(child, relationship='child')
                        fetch_and_add_children(parent_node.children[-1], max_depth=10)

                    hierarchy_data = parent_node.show_hierarchy(max_depth=10)

                # Redirect to user detail page after successful creation
                return redirect('user_detail',pk=request.user.pk)
        # If form is not valid, re-render the form with errors
    else:
        # Determine which form template to render based on the URL or some condition
        if request.path == '/home/user_detials.html':  # Adjust condition based on actual URL
            form = CreateUserForm()
            template = 'home/user_detials.html'
        else:
            form = CreateUserForm()
            template = 'home/UserRegistration.html'

    return render(request, template, {
        'form': form,
        'recruit': form, })



def user_detail(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user_instance = form.save(commit=False)
            password = form.cleaned_data['password']
            user_instance.set_password(password)

            if request.user.is_authenticated:
                user_instance.parent = request.user
            user_instance.save()

            # Assuming you want to show hierarchy data after successful form submission
            parent_node = UserNode(request.user, relationship='parent')
            children_under_parent = MyUser.objects.filter(parent=request.user)
                
            for child in children_under_parent:
                parent_node.add_child(child, relationship='child')
                fetch_and_add_children(parent_node.children[-1], max_depth=10)

            hierarchy_data = parent_node.show_hierarchy(max_depth=10)
            pk=user_instance.pk
            return redirect(reverse('apps_home:user_create_info', kwargs={'pk': user_instance.pk}))

            """return render(request, 'home/user_detials.html', {
                'hierarchy': hierarchy_data,
                'form': form,
            })"""
        # If form is not valid, render form with errors
    else:
        # GET request handling
        orders = Orders.objects.filter(user=request.user.id).values(
            'order_id',
            'order_date',
            'package_id__package_name',
            'package_id__package_price',
        )

        parent_node = UserNode(request.user, relationship='parent')
        children_under_parent = MyUser.objects.filter(parent=request.user)
        
        for child in children_under_parent:
            parent_node.add_child(child, relationship='child')
            fetch_and_add_children(parent_node.children[-1], max_depth=10)
        
        hierarchy_data = parent_node.show_hierarchy(max_depth=10)
        form = CreateUserForm()  # Initialize form for GET request

        return render(request, 'home/user_detials.html', {
            'hierarchy': hierarchy_data,
            'form': form,
            'orders': orders
        })

def create_user_details(request, pk):
    products = Products.objects.all().values()  # Assuming Products model exists
    user = get_object_or_404(MyUser, pk=pk)  # Retrieve user by primary key
    myAccount = Account.objects.filter(acc_holder=request.user).values('acc_type_id__name','cur_bal')
    form = keyBonusUpdate()
    print(myAccount)
    searched_user = None
    if request.method == 'POST':
        if 'search_button' in request.POST:
            form = keyBonusUpdate(request.POST)
            if form.is_valid():
                keyBonus_username = form.cleaned_data['keyBonus']
                try:
                    searched_user = MyUser.objects.get(username=keyBonus_username)
                except MyUser.DoesNotExist:
                    messages.error(request, f'User with username "{keyBonus_username}" does not exist.')
        elif 'save_button' in request.POST:
            keyBonus_username = request.POST.get('keyBonus_username')
            try:
                searched_user = MyUser.objects.get(username=keyBonus_username)
                user.keyBonus = searched_user
                user.save()
                messages.success(request, f'Key Bonus updated successfully for user "{user.username}".')
            # Redirect to home or appropriate URL
            except MyUser.DoesNotExist:
                messages.error(request, f'User with username "{keyBonus_username}" does not exist.')

    return render(request, 'home/user_details_create.html', {
        'products': products,
        'user': user,
        'form': form,
        'searched_user': searched_user,
        'myAccount': myAccount,
    })
class ProductView(CreateView):
    model = Products
    template_name = 'home/billing.html'
    success_url = reverse_lazy('apps_home:dashboard')
    form_class = CreateProducts 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Combine queryset data from multiple models
        context['product_form'] = CreateProducts()
        context['product_data'] = {
            'products': Products.objects.all().values(),
        }
        return context
    def get_template_names(self):
        if self.request.GET.get('template') == 'alternative':
            return ['home/alternative_billing.html']
        else:
            return [self.template_name]

class ProductDetials(DetailView):
    model = Products
    template_name = 'home/productDetials.html'

apps/templates/home/billing.html
{% extends 'layouts/mngt/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid py-4">
  <div class="row">
    <div class="col-lg-8">
      <div class="row">
                
        <div class="col-md-12 mb-lg-0 mb-4">
          <div class="card mt-4">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-6 d-flex align-items-center">
                  <h6 class="mb-0">Product List</h6>
                </div>


                <div class="col-6 text-end">
                  <a class="btn bg-gradient-dark mb-0" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fas fa-plus"></i>&nbsp;&nbsp;Add New Product</a>
                </div>
                

              </div>
            </div>
            <div class="card-body p-1">
              <div class="card">
                
                <div class="card-body px-0 pb-2">
                  <div class="table-responsive">
                    <table class="table align-items-center mb-0">
                      <thead>
                        <tr>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Product Id</th>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Product Name</th>
                          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Price</th>
                          
                        </tr>
                      </thead>
                      {% for prodlist in product_data.products %}
                      <tbody>
                        <tr>
                          <td>
                            <div class="d-flex px-2 py-1">
                            <a href="{% url 'apps_home:product_detail' pk=prodlist.product_id %}">
                              <div>
                                <img src="{% static 'img/small-logos/logo-xd.svg' %}" class="avatar avatar-sm me-3" alt="xd">
                              </div>
                            </a>

                              <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{prodlist.product_id}}</h6>
                              </div>
                            </div>
                          </td>
                         
                          <td class="align-middle text-center text-sm">
                            <span class="text-xs font-weight-bold"> {{prodlist.package_name}} </span>
                          </td>
                          <td class="align-middle">
                            <div class="progress-wrapper w-75 mx-auto">
                              <div class="progress-info">
                                <div class="progress-percentage">
                                  <span class="text-xs font-weight-bold">{{prodlist.package_price}}</span>
                                </div>
                              </div>
                              <div class="progress">
                                <div class="progress-bar bg-gradient-info w-60" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                              </div>
                            </div>
                          </td>
                        </tr>
                        <tr>
                          
                          
                          <td class="align-middle text-center text-sm">
                            <span class="text-xs font-weight-bold">  </span>
                          </td>
                          
                        </tr>
                      </tbody>
                      {% endfor%}
                    </table>
                  </div>
                </div>
              </div>
              
                
                  
                
                
              
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card h-100">
        <div class="card-header pb-0 p-3">
          <div class="row">
            <div class="col-6 d-flex align-items-center">
              <h6 class="mb-0">Products Transactions</h6>
            </div>
            <div class="col-6 text-end">
              <button class="btn btn-outline-primary btn-sm mb-0">View All</button>
            </div>
          </div>
        </div>
        <div class="card h-100 mb-4">
          <div class="card-header pb-0 px-3">
            <div class="row">
              <div class="col-md-6">
                <h6 class="mb-0"></h6>
              </div>
              <div class="col-md-6 d-flex justify-content-end align-items-center">
                <i class="far fa-calendar-alt me-2"></i>
                <small>23 - 30 March 2020</small>
              </div>
            </div>
          </div>
          <div class="card-body pt-4 p-3">
            <h6 class="text-uppercase text-body text-xs font-weight-bolder mb-3">Newest</h6>
            <ul class="list-group">
              <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                <div class="d-flex align-items-center">
                  <button class="btn btn-icon-only btn-rounded btn-outline-danger mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-down"></i></button>
                  <div class="d-flex flex-column">
                    <h6 class="mb-1 text-dark text-sm">Netflix</h6>
                    <span class="text-xs">27 March 2020, at 12:30 PM</span>
                  </div>
                </div>
                <div class="d-flex align-items-center text-danger text-gradient text-sm font-weight-bold">
                  - $ 2,500
                </div>
              </li>
              
            </ul>
            <h6 class="text-uppercase text-body text-xs font-weight-bolder my-3">Yesterday</h6>
            <ul class="list-group">
              <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                <div class="d-flex align-items-center">
                  <button class="btn btn-icon-only btn-rounded btn-outline-success mb-0 me-3 btn-sm d-flex align-items-center justify-content-center"><i class="fas fa-arrow-up"></i></button>
                  <div class="d-flex flex-column">
                    <h6 class="mb-1 text-dark text-sm">Stripe</h6>
                    <span class="text-xs">26 March 2020, at 13:45 PM</span>
                  </div>
                </div>
                <div class="d-flex align-items-center text-success text-gradient text-sm font-weight-bold">
                  + $ 750
                </div>
              </li>
              
            </ul>
          </div>
        </div>

       
      </div>
    </div>
  </div>





  
        <!-- Modal -->
       


  


{% endblock content %}

apps/templates/home/index.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_tags %}

{% block title %} Lifeplus {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-white" target="_blank" 
                 href="#">Life | Plus</a>
            </h1>
          
            <p class="lead text-white mt-3">
              LifePlus <a class="text-white" href="/">Presentation</a>. 
              <br /> 
            
              <pre>{{ hierarchy }}</pre>

            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="70">0</span>+</h1>
                <h5 class="mt-3">Sponsors </h5>
                <p class="text-sm"></p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo="15">0</span>+</h1>
                <h5 class="mt-3">Bonuses</h5>
                <p class="text-sm"></p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo="4">0 </h1>
                <h5 class="mt-3">Products</h5>
                <p class="text-sm"></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="P-4">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-12 ms-auto">
          
          <div class="row justify-content-left">
            {% for products in products.0 %}
            <div class="col-md-3 pd-4">
              <div class="card card-background card-background-mask-primary tilt" data-tilt>
                <div class="full-background" style="background-image: url('https://images.unsplash.com/photo-1579389083395-4507e98b5e67?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80')"></div>
                <div class="card-body pt-7 text-center">
                  <div class="icon icon-lg up mb-3 mt-3">
                    <svg width="25px" height="50px" viewBox="0 0 42 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <title>box-3d-50</title>
                      <g id="Basic-Elements" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Rounded-Icons" transform="translate(-2319.000000, -291.000000)" fill="#FFFFFF" fill-rule="nonzero">
                          <g id="Icons-with-opacity" transform="translate(1716.000000, 291.000000)">
                            <g id="box-3d-50" transform="translate(603.000000, 0.000000)">
                              <path d="M22.7597136,19.3090182 L38.8987031,11.2395234 C39.3926816,10.9925342 39.592906,10.3918611 39.3459167,9.89788265 C39.249157,9.70436312 39.0922432,9.5474453 38.8987261,9.45068056 L20.2741875,0.1378125 L20.2741875,0.1378125 C19.905375,-0.04725 19.469625,-0.04725 19.0995,0.1378125 L3.1011696,8.13815822 C2.60720568,8.38517662 2.40701679,8.98586148 2.6540352,9.4798254 C2.75080129,9.67332903 2.90771305,9.83023153 3.10122239,9.9269862 L21.8652864,19.3090182 C22.1468139,19.4497819 22.4781861,19.4497819 22.7597136,19.3090182 Z" id="Path"></path>
                              <path d="M23.625,22.429159 L23.625,39.8805372 C23.625,40.4328219 24.0727153,40.8805372 24.625,40.8805372 C24.7802551,40.8805372 24.9333778,40.8443874 25.0722402,40.7749511 L41.2741875,32.673375 L41.2741875,32.673375 C41.719125,32.4515625 42,31.9974375 42,31.5 L42,14.241659 C42,13.6893742 41.5522847,13.241659 41,13.241659 C40.8447549,13.241659 40.6916418,13.2778041 40.5527864,13.3472318 L24.1777864,21.5347318 C23.8390024,21.7041238 23.625,22.0503869 23.625,22.429159 Z" id="Path" opacity="0.7"></path>
                              <path d="M20.4472136,21.5347318 L1.4472136,12.0347318 C0.953235098,11.7877425 0.352562058,11.9879669 0.105572809,12.4819454 C0.0361450918,12.6208008 6.47121774e-16,12.7739139 0,12.929159 L0,30.1875 L0,30.1875 C0,30.6849375 0.280875,31.1390625 0.7258125,31.3621875 L19.5528096,40.7750766 C20.0467945,41.0220531 20.6474623,40.8218132 20.8944388,40.3278283 C20.963859,40.1889789 21,40.0358742 21,39.8806379 L21,22.429159 C21,22.0503869 20.7859976,21.7041238 20.4472136,21.5347318 Z" id="Path" opacity="0.7"></path>
                            </g>
                          </g>
                        </g>
                      </g>
                    </svg>
                  </div>
                  <h2 class="text-white up mb-0">{{products.package_name}} <br />$ {{products.package_price}}</h2>
                  <a href="{% url 'apps_home:client_ProDetail' pk=products.product_id %}" class="btn btn-outline-white mt-5 up btn-round"><h2 class="text-white up mb-0">Purchase</h2></a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
  


  <!-- -------- START Content Presentation Docs ------- -->


  <!-- -------- END Content Presentation Docs ------- -->
  

  <!-- START Section Content W/ 2 images aside of icon title description -->
  

  <!-- END Section Content -->
  <!-- -------   START PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->
  

  <!-- -------   END PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->
  
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends 'layouts/base.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} contact-us {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-light.html" %}

  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="{{ ASSETS_ROOT }}/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">
                    Error 404 
                </h3>
                <p class="mb-0">
                  The page you're looking for doesn't exist.
                </p>
              </div>
              <form role="form" id="contact-form" method="post" autocomplete="off">
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <a href="/" class="btn bg-gradient-primary mt-3 mb-0">HOME</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}